window.AMAHARA = window.AMAHARA || {};
AMAHARA.Audio = class {
  constructor(){this.ctx=null;this.master=null;this.musicTimer=0;this.enabled=true}
  init(){if(this.ctx)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;this.ctx=new C();this.master=this.ctx.createGain();this.master.gain.value=.18;this.master.connect(this.ctx.destination)}
  tone(freq=220,dur=.08,type='square',vol=.18,slide=0){if(!this.enabled)return;this.init();if(!this.ctx)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,freq+slide),t+dur);g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.001,t+dur);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+dur+.02)}
  noise(dur=.06,vol=.08){this.init();if(!this.ctx)return;const n=Math.ceil(this.ctx.sampleRate*dur),b=this.ctx.createBuffer(1,n,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);const s=this.ctx.createBufferSource(),g=this.ctx.createGain();s.buffer=b;g.gain.value=vol;s.connect(g);g.connect(this.master);s.start()}
  sfx(name){switch(name){case'slash':this.tone(330,.07,'sawtooth',.13,-140);this.noise(.04,.04);break;case'heavy':this.tone(180,.11,'square',.17,-80);this.noise(.08,.06);break;case'hit':this.tone(90,.055,'square',.15,-35);this.noise(.035,.09);break;case'dash':this.tone(520,.09,'triangle',.1,-240);break;case'magic1':this.tone(700,.18,'triangle',.13,-300);break;case'magic2':this.tone(140,.35,'sine',.16,180);break;case'zombie':this.tone(72,.24,'sawtooth',.08,-12);break;case'boss':this.tone(55,.7,'sawtooth',.18,-10);break;case'ui':this.tone(480,.05,'square',.07,50);break;case'shrine':this.tone(660,.6,'sine',.11,-120);setTimeout(()=>this.tone(880,.55,'sine',.08,-200),100);break}}
  update(dt,mode='calm'){if(!this.ctx)return;this.musicTimer-=dt;if(this.musicTimer>0)return;this.musicTimer=mode==='boss'?.42:mode==='corrupt'?.75:1.2;const notes=mode==='boss'?[82,98,110,123]:mode==='corrupt'?[110,130,146,164]:[164,196,220,246];this.tone(notes[(Math.random()*notes.length)|0],mode==='boss'?.3:.55,'sine',.025,0)}
};
