window.AMAHARA = window.AMAHARA || {};
AMAHARA.Game = class {
  constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.ctx.imageSmoothingEnabled=false;this.input=new AMAHARA.Input();this.audio=new AMAHARA.Audio();this.world=new AMAHARA.World(this);this.player=new AMAHARA.Player(this);this.enemies=[];this.boss=null;this.npc={x:700,y:1660,name:'Yuna',role:'Guardiã do Santuário'};this.projectiles=[];this.particles=[];this.rings=[];this.camera={x:260,y:1505};this.shake=0;this.hitstop=0;this.paused=true;this.started=false;this.dialogueActive=false;this.dialogueQueue=[];this.cutscene=false;this.story=0;this.kills=0;this.checkpoint={x:500,y:1640};this.objective='';this.spawnedForest=false;this.spawnedShrine=false;this.bossTriggered=false;this.bossDefeated=false;this.enemyAttackCooldown=0;this.arenaBarrier=null;this.debug=false;this.last=performance.now();this.bindUI();this.installTestAPI()}
  bindUI(){const q=id=>document.getElementById(id);q('playBtn').onclick=()=>this.start();q('controlsBtn').onclick=()=>this.showPanel('controls');document.querySelector('[data-close="controls"]').onclick=()=>this.showPanel(this.started&&this.paused?'pause':'menu');q('resumeBtn').onclick=()=>this.togglePause(false);q('pauseControlsBtn').onclick=()=>this.showPanel('controls');q('restartBtn').onclick=()=>this.restart();q('menuBtn').onclick=()=>this.returnMenu();q('victoryRestartBtn').onclick=()=>this.restart(true);q('victoryMenuBtn').onclick=()=>this.returnMenu()}
  showPanel(id){for(const p of ['menu','controls','pause','victory'])document.getElementById(p).classList.add('hidden');document.getElementById(id).classList.remove('hidden')}
  start(){this.audio.init();this.audio.sfx('ui');document.getElementById('menu').classList.add('hidden');this.started=true;this.paused=false;this.resetState();this.openDialogue([
    ['Yuna','Ren, o arroz ainda está no fogo. Pela primeira vez em semanas, a aldeia parece em paz.'],
    ['Ren','Paz demais. Os corvos sumiram da encosta.'],
    ['Yuna','Então ouviu também... o sino do santuário tocou sozinho.'],
    ['','Um grito corta a rua. Metal arrasta na terra. Um guerreiro morto atravessa o portão.']
  ],()=>{this.story=1;this.objective='Defenda Amahara — derrote os invasores (0/5)';this.spawnVillageWave()})}
  resetState(){this.world=new AMAHARA.World(this);this.player=new AMAHARA.Player(this);this.enemies=[];this.boss=null;this.projectiles=[];this.particles=[];this.rings=[];this.camera={x:260,y:1505};this.story=0;this.kills=0;this.checkpoint={x:500,y:1640};this.objective='';this.spawnedForest=false;this.spawnedShrine=false;this.bossTriggered=false;this.bossDefeated=false;this.enemyAttackCooldown=0;this.arenaBarrier=null;this.cutscene=false;this.dialogueActive=false;document.getElementById('dialogue').classList.add('hidden');document.getElementById('victory').classList.add('hidden')}
  restart(skipIntro=false){this.showPanel('pause');document.getElementById('pause').classList.add('hidden');this.started=true;this.paused=false;this.resetState();if(skipIntro){this.story=1;this.objective='Defenda Amahara — derrote os invasores (0/5)';this.spawnVillageWave()}else this.start()}
  returnMenu(){this.started=false;this.paused=true;this.resetState();this.showPanel('menu')}
  spawnVillageWave(){[[645,1635,'swordsman'],[735,1700,'runner'],[665,1540,'swordsman'],[820,1760,'heavy'],[900,1600,'archer']].forEach(a=>this.spawnEnemy(a[2],a[0],a[1]));this.audio.sfx('zombie')}
  spawnForest(){if(this.spawnedForest)return;this.spawnedForest=true;[[1260,1370,'runner'],[1320,1450,'swordsman'],[1680,1300,'archer'],[1780,1450,'swordsman'],[1980,1280,'heavy'],[2180,1390,'runner']].forEach(a=>this.spawnEnemy(a[2],a[0],a[1]))}
  spawnShrine(){if(this.spawnedShrine)return;this.spawnedShrine=true;[[2380,900,'swordsman'],[2470,980,'heavy'],[2700,900,'archer'],[2820,830,'runner']].forEach(a=>this.spawnEnemy(a[2],a[0],a[1]))}
  spawnEnemy(type,x,y){const e=new AMAHARA.Enemy(this,type,x,y);this.enemies.push(e);return e}
  requestEnemyAttack(e){if(this.enemyAttackCooldown>0)return false;const active=this.enemies.filter(x=>!x.dead&&['telegraph','attack'].includes(x.state)).length;if(active>=2)return false;this.enemyAttackCooldown=.22;return true}
  onEnemyKilled(e){this.kills++;if(this.story===1){const n=Math.min(this.kills,5);this.objective=`Defenda Amahara — derrote os invasores (${n}/5)`;if(this.enemies.filter(x=>!x.dead).length===0){this.story=2;this.objective='Fale com Yuna';this.toast('A última lâmina morta cai. Yuna chama você.')}}}
  onPlayerDeath(){this.openDialogue([['','A marca divina apaga por um instante...']],()=>setTimeout(()=>this.respawn(),250))}
  respawn(){this.player.reset(this.checkpoint.x,this.checkpoint.y);this.projectiles=[];this.toast('Você despertou no último santuário.')}
  onBossDeath(){this.bossDefeated=true;this.objective='';this.cutscene=true;this.arenaBarrier=null;this.audio.sfx('boss');this.spawnBurst(this.boss.x,this.boss.y,'#c75a8c',36);this.rings.push({x:this.boss.x,y:this.boss.y,r:8,max:92,life:.9,color:'#d78bb0'});setTimeout(()=>this.openDialogue([
    ['General Jinzō','Eu não os despertei... eu apenas ouvi o chamado sob a montanha.'],
    ['Ren','Quem chamou os mortos?'],
    ['General Jinzō','Três sinos. Três sepulturas. E alguém que conhece o sangue em suas veias...'],
    ['','O estandarte se desfaz em cinza violeta. Ao longe, três sinos respondem.']
  ],()=>{this.cutscene=false;this.paused=true;this.showPanel('victory')}),900)}
  openDialogue(lines,onDone=null){this.dialogueQueue=lines.slice();this.dialogueDone=onDone;this.dialogueActive=true;this.nextDialogue()}
  nextDialogue(){if(!this.dialogueQueue.length){this.dialogueActive=false;document.getElementById('dialogue').classList.add('hidden');const cb=this.dialogueDone;this.dialogueDone=null;if(cb)cb();return}const [s,t]=this.dialogueQueue.shift();document.getElementById('speaker').textContent=s;document.getElementById('dialogueText').textContent=t;document.getElementById('dialogue').classList.remove('hidden')}
  interact(){const it=this.world.nearestInteractable(this.player);if(!it)return;const id=it.id;if(id==='npcYuna'){if(this.story===2){this.openDialogue([['Yuna','As armaduras trazem o selo do general Jinzō. Ele morreu há oitenta anos, no vale acima do santuário.'],['Ren','Então alguém abriu uma sepultura de guerra.'],['Yuna','Siga o rastro. E Ren... sua marca está brilhando como na noite em que sua mãe o trouxe até mim.']],()=>{this.story=3;this.objective='Siga o rastro pela floresta até o santuário';this.spawnForest()})}else this.openDialogue([['Yuna','Não deixe a raiva escolher o ritmo da sua espada.']])}
    else if(id==='checkpoint'){this.checkpoint={x:2575,y:820};this.player.hp=this.player.maxHp;this.player.energy=this.player.maxEnergy;this.audio.sfx('shrine');this.toast('Santuário purificado — checkpoint restaurado');if(this.story<4){this.story=4;this.objective='Atravesse o torii e encontre a origem da corrupção';this.openDialogue([['Ren','A água de purificação está negra... mas a chama ainda responde.'],['','A marca dourada no braço de Ren reage a algo atrás do último torii.']])}}
    else if(id==='inscription')this.openDialogue([['Inscrição','“Quando o estandarte sem senhor se erguer, os que morreram pela guerra esquecerão que morreram.”']]);
    else if(id==='secretAltar'){if(!this.player.hasSecret){this.player.hasSecret=true;this.player.maxEnergy+=25;this.player.energy=this.player.maxEnergy;this.audio.sfx('shrine');this.toast('SEGREDO — Fragmento do Estandarte: +25 Energia Divina');this.openDialogue([['Ren','Este altar não pertence ao santuário. Alguém o escondeu depois da guerra.']])}else this.toast('O altar está silencioso.')}}
  triggerBoss(){if(this.bossTriggered)return;this.bossTriggered=true;this.cutscene=true;this.objective='';this.arenaBarrier={x:2978,y:520,w:18,h:330,type:'sealedGate'};this.player.x=3060;this.player.y=670;this.boss=new AMAHARA.Boss(this,3235,610);this.audio.sfx('boss');this.openDialogue([['','O torii atrás de Ren se fecha em chamas negras.'],['General Jinzō','Sangue do campo de batalha... finalmente veio até mim.'],['Ren','Você trouxe os mortos para Amahara.'],['General Jinzō','Não. Eu fui o primeiro deles.']],()=>{this.cutscene=false;this.boss.state='recover';this.boss.timer=.5;this.objective='Derrote General Jinzō — O Estandarte Oco'})}
  update(dt){this.input.update();if(this.input.pressed&&this.input.pressed.has('F3')){this.debug=!this.debug;this.input.pressed.delete('F3')}if(this.started&&this.input.take('pause')&&!this.dialogueActive){this.togglePause(!this.paused);this.input.endFrame();return}if(this.dialogueActive){if(this.input.take('interact')||this.input.take('light'))this.nextDialogue();this.input.endFrame();return}if(this.paused||!this.started){this.input.endFrame();return}if(this.hitstop>0){this.hitstop-=dt;this.input.endFrame();return}this.enemyAttackCooldown=Math.max(0,this.enemyAttackCooldown-dt);this.player.update(dt,this.input);if(this.input.take('interact'))this.interact();if(this.player.x>1120&&this.story>=3)this.spawnForest();if(this.player.x>2280&&this.player.y<1150&&this.story>=3)this.spawnShrine();if(this.player.x>2960&&this.player.y<900&&this.story>=4)this.triggerBoss();for(const e of this.enemies)e.update(dt);this.enemies=this.enemies.filter(e=>!e.dead||e.deathTimer>0);if(this.boss)this.boss.update(dt);this.updateProjectiles(dt);this.updateFx(dt);this.updateCamera(dt);this.audio.update(dt,this.boss&&!this.boss.dead?'boss':this.player.x>2250?'corrupt':'calm');this.input.endFrame()}
  togglePause(v){if(!this.started)return;this.paused=v;if(v)this.showPanel('pause');else document.getElementById('pause').classList.add('hidden')}
  updateProjectiles(dt){for(const p of this.projectiles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(this.world.isWaterAt(p.x,p.y)&&p.type!=='grave')p.life=0;if(p.type==='playerSlash'){for(const e of this.enemies)if(!e.dead&&!p.hit.has(e.id)&&AMAHARA.U.rects({x:p.x-p.w/2,y:p.y-p.h/2,w:p.w,h:p.h},e.hurtbox())){p.hit.add(e.id);AMAHARA.Combat.damage(this,e,p.damage,this.player,80,'proj');p.life=0}if(this.boss&&!this.boss.dead&&AMAHARA.U.rects({x:p.x-p.w/2,y:p.y-p.h/2,w:p.w,h:p.h},this.boss.hurtbox())){AMAHARA.Combat.damage(this,this.boss,p.damage,this.player,35,'proj');p.life=0}}else if((p.type==='arrow'||p.type==='grave')&&!this.player.dead&&AMAHARA.U.rects({x:p.x-p.w/2,y:p.y-p.h/2,w:p.w,h:p.h},this.player.hurtbox())){AMAHARA.Combat.damage(this,this.player,p.damage,p.owner,p.type==='grave'?80:45,'ep');p.life=0}}this.projectiles=this.projectiles.filter(p=>p.life>0&&p.x>0&&p.y>0&&p.x<this.world.w&&p.y<this.world.h)}
  updateFx(dt){for(const p of this.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96}this.particles=this.particles.filter(p=>p.life>0);for(const r of this.rings){if(r.startLife==null)r.startLife=r.life;r.life-=dt}this.rings=this.rings.filter(r=>r.life>0);this.shake=Math.max(0,this.shake-dt*18)}
  updateCamera(dt){const tx=this.player.x-240,ty=this.player.y-135;this.camera.x=AMAHARA.U.clamp(AMAHARA.U.lerp(this.camera.x,tx,1-Math.pow(.001,dt)),0,this.world.w-480);this.camera.y=AMAHARA.U.clamp(AMAHARA.U.lerp(this.camera.y,ty,1-Math.pow(.001,dt)),0,this.world.h-270)}
  spawnHit(x,y,c){this.spawnBurst(x,y,c,6)} spawnTrail(x,y,c){this.particles.push({x,y:y+4,vx:(Math.random()-.5)*8,vy:(Math.random()-.5)*8,life:.18,max:.18,color:c,size:2})}
  spawnBurst(x,y,c,n=10){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=25+Math.random()*75;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.22+Math.random()*.28,max:.5,color:c,size:1+Math.random()*2|0})}}
  toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.remove('hidden');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>el.classList.add('hidden'),1800)}
  drawNPC(ctx){const n=this.npc;ctx.save();ctx.translate(Math.round(n.x),Math.round(n.y));ctx.fillStyle='#171817';ctx.fillRect(-7,7,14,3);ctx.fillStyle='#536a78';ctx.fillRect(-7,-9,14,16);ctx.fillStyle='#c9a487';ctx.fillRect(-4,-15,8,6);ctx.fillStyle='#36302c';ctx.fillRect(-5,-18,10,4);ctx.fillStyle='#d8c28a';ctx.fillRect(5,-8,2,12);ctx.restore()}
  drawProjectile(ctx,p){ctx.save();ctx.translate(Math.round(p.x),Math.round(p.y));if(p.type==='playerSlash'){ctx.fillStyle='#b8f2ed';ctx.fillRect(-10,-2,20,4);ctx.fillStyle='#f2e7b8';ctx.fillRect(-6,-4,12,2)}else if(p.type==='arrow'){ctx.fillStyle='#c3a16a';ctx.fillRect(-5,-1,10,2)}else{ctx.fillStyle='#8f4778';ctx.fillRect(-4,-4,8,8);ctx.fillStyle='#d27baa';ctx.fillRect(-2,-2,4,4)}ctx.restore()}
  render(){const ctx=this.ctx;ctx.clearRect(0,0,480,270);let sx=this.shake?(Math.random()-.5)*this.shake:0,sy=this.shake?(Math.random()-.5)*this.shake:0;ctx.save();ctx.translate(-Math.floor(this.camera.x)+Math.floor(sx),-Math.floor(this.camera.y)+Math.floor(sy));this.world.drawGround(ctx,this.camera);const drawables=[];for(const p of this.world.visibleProps(this.camera))drawables.push({y:p.y,draw:()=>this.world.drawProp(ctx,p)});drawables.push({y:this.npc.y,draw:()=>this.drawNPC(ctx)});for(const e of this.enemies)drawables.push({y:e.y,draw:()=>e.draw(ctx)});if(this.boss)drawables.push({y:this.boss.y,draw:()=>this.boss.draw(ctx)});drawables.push({y:this.player.y,draw:()=>this.player.draw(ctx)});drawables.sort((a,b)=>a.y-b.y);for(const d of drawables)d.draw();for(const r of this.rings){const k=1-r.life/Math.max(r.life,.0001);ctx.strokeStyle=r.color;ctx.lineWidth=2;ctx.beginPath();const rr=Math.max(1,r.max*(1-r.life/Math.max(.001,r.startLife||r.life)));ctx.arc(r.x,r.y,rr,0,Math.PI*2);ctx.stroke()}for(const p of this.projectiles)this.drawProjectile(ctx,p);for(const p of this.particles){ctx.globalAlpha=Math.max(0,p.life/(p.max||.5));ctx.fillStyle=p.color;ctx.fillRect(Math.round(p.x),Math.round(p.y),p.size,p.size)}ctx.globalAlpha=1;ctx.restore();this.drawHUD(ctx)}
  drawHUD(ctx){if(!this.started)return;const p=this.player;ctx.fillStyle='#101310db';ctx.fillRect(8,8,144,39);ctx.fillStyle='#d6c39a';ctx.font='7px monospace';ctx.fillText('REN KUROGANE',14,17);ctx.fillStyle='#3a1717';ctx.fillRect(14,22,120,7);ctx.fillStyle='#b94b46';ctx.fillRect(14,22,120*(p.hp/p.maxHp),7);ctx.fillStyle='#1f3540';ctx.fillRect(14,33,120,6);ctx.fillStyle='#67c7bf';ctx.fillRect(14,33,120*(p.energy/p.maxEnergy),6);ctx.fillStyle='#d6c39a';ctx.fillText(`${Math.ceil(p.hp)}/${p.maxHp}`,138,28);ctx.fillText(`DIV ${Math.floor(p.energy)}/${p.maxEnergy}`,138,39);ctx.textAlign='center';ctx.fillStyle='#111510dd';ctx.fillRect(160,8,160,18);ctx.fillStyle='#eadcb9';ctx.font='7px monospace';ctx.fillText(this.objective||'',240,19);ctx.textAlign='left';const it=this.world.nearestInteractable(p);if(it&&!this.dialogueActive){ctx.fillStyle='#111510df';ctx.fillRect(176,238,128,20);ctx.fillStyle='#e9d59c';ctx.textAlign='center';ctx.fillText(`F / X — ${it.label}`,240,251);ctx.textAlign='left'}ctx.fillStyle='#111510d9';ctx.fillRect(336,8,136,28);ctx.fillStyle='#eadcb9';ctx.fillText(`Q Corte ${p.magic1Cooldown>0?p.magic1Cooldown.toFixed(1):'OK'}`,342,18);ctx.fillText(`E Selo  ${p.magic2Cooldown>0?p.magic2Cooldown.toFixed(1):'OK'}`,342,29);if(this.boss&&!this.boss.dead){ctx.fillStyle='#0c0d0cdd';ctx.fillRect(82,243,316,19);ctx.fillStyle='#d9c4a0';ctx.textAlign='center';ctx.fillText(`GENERAL JINZŌ — ESTANDARTE OCO · FASE ${this.boss.phase}`,240,250);ctx.fillStyle='#38172a';ctx.fillRect(98,254,284,5);ctx.fillStyle='#a7446b';ctx.fillRect(98,254,284*(this.boss.hp/this.boss.maxHp),5);ctx.textAlign='left'}if(this.debug){ctx.fillStyle='#000c';ctx.fillRect(5,220,150,45);ctx.fillStyle='#9fe594';ctx.fillText(`P ${p.x|0},${p.y|0} ${p.state}`,8,229);ctx.fillText(`Enemies ${this.enemies.filter(e=>!e.dead).length} story ${this.story}`,8,239);ctx.fillText(`Pad ${this.input.anyGamepad?'YES':'NO'}`,8,249)}}
  frame(t){const dt=Math.min(.033,(t-this.last)/1000||.016);this.last=t;this.update(dt);this.render();requestAnimationFrame(x=>this.frame(x))}
  installTestAPI(){window.__GAME_TEST__={state:()=>({started:this.started,paused:this.paused,story:this.story,objective:this.objective,player:{x:this.player.x,y:this.player.y,hp:this.player.hp,energy:this.player.energy,state:this.player.state,maxEnergy:this.player.maxEnergy},enemies:this.enemies.filter(e=>!e.dead).map(e=>({id:e.id,type:e.type,x:e.x,y:e.y,hp:e.hp,state:e.state})),boss:this.boss?{hp:this.boss.hp,phase:this.boss.phase,state:this.boss.state,dead:this.boss.dead}:null,victory:this.bossDefeated}),press:(code)=>{dispatchEvent(new KeyboardEvent('keydown',{code}));dispatchEvent(new KeyboardEvent('keyup',{code}))},teleport:(x,y)=>{this.player.x=x;this.player.y=y},damageBoss:(n)=>{if(this.boss)this.boss.takeDamage(n,this.player,0,'test')},killEnemies:()=>{for(const e of this.enemies.slice())if(!e.dead)e.takeDamage(999,this.player,0,'test')},setDebug:(v)=>this.debug=!!v,interact:()=>this.interact(),start:()=>this.start()}}
};
