extends "res://tests/sample_suite.gd"

func run(host) -> void:
	game = host
	game.start_sample()
	while game.ui.dialog.visible: game.next_dialogue()
	game.director.active = {"village":[],"forest":[],"bridge":[],"corruption":[],"elite":[]}
	await ticks(3)
	game.player.restore(Vector2(2700,440))
	game.player.invuln = 0
	var boss: GeneralJinzo = game.boss
	boss.state = "recover"
	boss.set_physics_process(false)
	game.hazard(boss,game.player.position,40,13,.5)
	await seconds(.3)
	check("hazard_no_damage_before_cue",game.player.hp == 100)
	await seconds(.3)
	check("hazard_active_damage",game.player.hp == 87)
	await seconds(.5)
	check("hazard_single_hit_cleanup",game.player.hp == 87 and game.projectiles.get_child_count() == 0)
	game.player.restore(Vector2(870,300))
	game.hostile_shot(boss,Vector2(1040,290),Vector2.LEFT,13)
	await seconds(1.2)
	check("arrow_blocked_by_water_wall",game.player.hp == 100 and game.projectiles.get_child_count() == 0)
	var archer: VillageEnemy = game.spawn_enemy(Vector2(1020,300),"archer")
	check("archer_line_of_sight_blocked",not archer.line_of_sight())
	archer.queue_free()
	game.player.restore(Vector2(1770,520))
	var runner: VillageEnemy = game.spawn_enemy(Vector2(1610,465),"runner")
	var start := runner.position
	await seconds(2)
	check("navigation_around_rock",runner.position.distance_to(game.player.position) < start.distance_to(game.player.position)-50)
	runner.queue_free()
	await ticks(3)
	game.player.restore(Vector2(2700,440))
	boss.hp = 240
	boss.set_physics_process(true)
	await ticks(3)
	game.set_paused(true)
	var phase_timer := boss.timer
	await seconds(.2)
	check("pause_freezes_boss_transition",boss.state == "transition" and boss.timer == phase_timer)
	game.set_paused(false)
	await seconds(2)
	for id in boss.patterns:
		game.player.restore(Vector2(2700,440))
		boss.position = Vector2(2790,440)
		boss.begin_pattern(id)
		await seconds(boss.pattern.windup+.04)
		check("phase2_pattern_"+id,boss.phase == 2 and boss.state == "attack")
		await seconds(boss.pattern.active+.05)
		check("phase2_recovery_"+id,boss.state == "recover")
		game.clear_effects()
		for e in boss.summons:
			if is_instance_valid(e): e.queue_free()
		boss.summons.clear()
	check("transition_still_once",boss.transitions == 1)
	game.story.restore({"stage":5,"checkpoint":"sanctuary","completed":["village","elite"],"upgrades":[],"shortcut":false})
	game.boss_active = true
	game.sync_progress()
	game.player.invuln = 0
	game.player.receive_hit(999,boss,0,0)
	await seconds(1.3)
	check("actual_boss_death_respawn",not game.player.dead and game.player.hp == 100 and game.player.position.distance_to(Vector2(2208,424)) < 2)
	check("actual_boss_attempt_reset",game.boss.phase == 1 and game.boss.hp == 480 and game.boss.summons.is_empty() and game.projectiles.get_child_count() == 0 and not game.world.gate_closed.arena)
	game.player.position = Vector2(2208,424)
	await ticks(3)
	game.interact()
	var cp: Dictionary = game.story.snapshot()
	game.interact()
	check("repeated_checkpoint_idempotent",game.story.snapshot() == cp)
	game.player.position = Vector2(1490,275)
	game.player.hp = 40
	await ticks(3)
	game.interact()
	while game.ui.dialog.visible: game.next_dialogue()
	check("memorial_recovery_and_item",game.player.hp == 75 and "memorial" in game.story.upgrades)
	game.interact()
	while game.ui.dialog.visible: game.next_dialogue()
	check("memorial_reward_once",game.player.hp == 75 and game.story.upgrades.count("memorial") == 1)
	game.boss.state = "chase"
	game.boss.invuln = 0
	game.boss.receive_hit(999,game.player,0,1)
	check("boss_victory_unlocks",game.story.stage == 6 and not game.world.gate_closed.arena and game.ui.dialog.visible)
	while game.ui.dialog.visible: game.next_dialogue()
	check("victory_ui",game.ending_seen and get_tree().paused and is_instance_valid(game.ui.modal))
	game.return_menu()
	game.start_sample(true)
	check("victory_save_reopen",game.story.stage == 6 and not is_instance_valid(game.boss))
	game.open_dialogue([["TEST","Cancelled callback"]],func(): game.story.stage = 99)
	game.return_menu()
	game.start_sample()
	while game.ui.dialog.visible: game.next_dialogue()
	check("restart_cancels_old_callback",game.story.stage == 0)
	var fail := checks.filter(func(c): return c.result == "FAIL").size()
	var f := FileAccess.open(game.evidence_dir+"/advanced_qa.json",FileAccess.WRITE)
	f.store_string(JSON.stringify({"pass":checks.size()-fail,"fail":fail,"checks":checks},"\t"))
	f.close()
	print("ADVANCED_QA ",checks.size()-fail," PASS / ",fail," FAIL")
	game.close_game()
