window.AMAHARA = window.AMAHARA || {};
AMAHARA.Boss = class {
  constructor(game,x,y){this.game=game;this.id='boss';this.x=x;this.y=y;this.w=26;this.h=34;this.maxHp=AMAHARA.BALANCE.boss.hp;this.hp=this.maxHp;this.speed=AMAHARA.BALANCE.boss.speed;this.damage=AMAHARA.BALANCE.boss.damage;this.phase=1;this.state='intro';this.timer=1.5;this.dead=false;this.invuln=1.7;this.flash=0;this.attackName='';this.attackId=0;this.hitDone=false;this.facing='left';this.chargeDir={x:-1,y:0};this.summoned=false;this.deathTimer=0}
  hurtbox(){return{x:this.x-this.w/2,y:this.y-this.h/2,w:this.w,h:this.h}}
  takeDamage(amount,source,knock=0,id=''){if(this.dead||this.invuln>0)return false;this.hp-=amount;this.flash=.11;this.invuln=.05;if(this.phase===1&&this.hp/this.maxHp<=AMAHARA.BALANCE.boss.phase2){this.phase=2;this.state='transition';this.timer=1.7;this.invuln=1.8;this.game.toast('FASE 2 — O ESTANDARTE DESPERTOU');this.game.spawnBurst(this.x,this.y,'#a24a73',32);this.game.shake=8;this.game.audio.sfx('boss')}if(this.hp<=0){this.hp=0;this.dead=true;this.state='dead';this.deathTimer=2.4;this.game.onBossDeath()}return true}
  update(dt){this.invuln=Math.max(0,this.invuln-dt);this.flash=Math.max(0,this.flash-dt);if(this.dead){this.deathTimer-=dt;return}const p=this.game.player,d=AMAHARA.U.dist(this,p);this.facing=p.x>this.x?'right':'left';if(this.state==='intro'){this.timer-=dt;if(this.timer<=0)this.recover(.6);return}if(this.state==='transition'){this.timer-=dt;if(this.timer<=0){if(!this.summoned){this.summoned=true;this.game.spawnEnemy('runner',this.x-55,this.y+35);this.game.spawnEnemy('swordsman',this.x+55,this.y+35)}this.recover(.55)}return}if(this.state==='recover'){this.timer-=dt;if(this.timer<=0)this.chooseAttack(d);return}if(this.state==='chase'){if(d>66){const n=AMAHARA.U.norm(p.x-this.x,p.y-this.y);this.game.world.move(this,n.x*this.speed*dt,n.y*this.speed*dt)}else this.chooseAttack(d);return}if(this.state==='telegraph'){this.timer-=dt;if(this.timer<=0)this.executeAttack();return}if(this.state==='attack'){this.updateAttack(dt);return}}
  chooseAttack(d){if(d>150){this.state='chase';return}const r=Math.random();let name;if(this.phase===1)name=r<.46?'combo':r<.76?'charge':'aoe';else name=r<.30?'combo':r<.53?'charge':r<.76?'aoe':'grave';this.telegraph(name)}
  telegraph(name){this.attackName=name;this.state='telegraph';this.timer=name==='aoe'?.75:name==='charge'?.55:name==='grave'?.8:.34;this.game.rings.push({x:this.x,y:this.y,r:6,max:name==='aoe'?78:36,life:this.timer,color:name==='grave'?'#9d477b':'#c66b54'})}
  executeAttack(){this.state='attack';this.attackId++;this.hitDone=false;const p=this.game.player;if(this.attackName==='charge'){this.chargeDir=AMAHARA.U.norm(p.x-this.x,p.y-this.y);this.timer=.38}else if(this.attackName==='combo')this.timer=.52;else if(this.attackName==='aoe'){this.timer=.18;this.areaHit(78,this.phase===2?23:19,125)}else if(this.attackName==='grave'){this.timer=.28;for(let i=0;i<8;i++){const a=i*Math.PI/4+(this.phase===2?.15:0);this.game.projectiles.push({type:'grave',x:this.x,y:this.y-8,vx:Math.cos(a)*105,vy:Math.sin(a)*105,w:9,h:9,life:2.7,damage:12,owner:this,hit:new Set()})}this.game.spawnBurst(this.x,this.y,'#9d477b',20)}}
  updateAttack(dt){this.timer-=dt;const p=this.game.player;if(this.attackName==='charge'){this.game.world.move(this,this.chargeDir.x*210*dt,this.chargeDir.y*210*dt);if(!this.hitDone&&AMAHARA.U.rects(this.hurtbox(),p.hurtbox())){this.hitDone=true;AMAHARA.Combat.damage(this.game,p,22,this,150,this.attackId)}}else if(this.attackName==='combo'){const rel=.52-this.timer;const hitWindows=[[.08,.14],[.22,.29],[.38,.46]];for(let i=0;i<hitWindows.length;i++){if(rel>=hitWindows[i][0]&&rel<=hitWindows[i][1]&&!this['h'+i]){this['h'+i]=true;const r={x:this.x+(this.facing==='right'?8:-50),y:this.y-24,w:42,h:42};if(AMAHARA.U.rects(r,p.hurtbox()))AMAHARA.Combat.damage(this.game,p,10+(i===2?8:0),this,i===2?120:70,this.attackId+'-'+i)}}}if(this.timer<=0){this.h0=this.h1=this.h2=false;this.recover(this.phase===2?.55:.78)}}
  areaHit(rad,dmg,knock){const p=this.game.player;if(AMAHARA.U.dist(this,p)<=rad)AMAHARA.Combat.damage(this.game,p,dmg,this,knock,this.attackId)}
  recover(t){this.state='recover';this.timer=t}
  draw(ctx){const x=Math.round(this.x),y=Math.round(this.y);ctx.save();ctx.translate(x,y);if(this.flash>0)ctx.globalAlpha=.55;ctx.fillStyle='#161616';ctx.fillRect(-16,13,32,6);ctx.fillStyle=this.phase===2?'#54273f':'#323c42';ctx.fillRect(-13,-14,26,28);ctx.fillStyle='#636b70';ctx.fillRect(-17,-13,34,8);ctx.fillStyle='#73534a';ctx.fillRect(-8,-24,16,10);ctx.fillStyle='#2a2428';ctx.fillRect(-12,-29,24,6);ctx.fillStyle='#b14661';ctx.fillRect(-2,-20,4,4);ctx.fillStyle='#a78959';ctx.fillRect(13,-9,4,23);ctx.fillStyle='#c8c6b9';ctx.fillRect(this.facing==='right'?16:-38,-6,22,3);ctx.fillStyle=this.phase===2?'#c14e83':'#7d3252';ctx.fillRect(-5,-38,10,10);if(this.state==='telegraph'){ctx.fillStyle='#efc56b';ctx.fillRect(-18,-43,36,3)}ctx.restore()}
};
