window.AMAHARA = window.AMAHARA || {};
let enemySeq=1;
AMAHARA.Enemy = class {
  constructor(game,type,x,y){this.game=game;this.type=type;this.id='e'+enemySeq++;this.x=x;this.y=y;this.w=14;this.h=18;const d=AMAHARA.BALANCE.enemies[type];Object.assign(this,{maxHp:d.hp,hp:d.hp,speed:d.speed,damage:d.damage,range:d.range,detection:d.detection,disengage:d.disengage,windup:d.windup,recovery:d.recovery,color:d.color});this.state='idle';this.timer=Math.random();this.dead=false;this.invuln=0;this.stun=0;this.flash=0;this.attackId=0;this.hitDone=false;this.facing='left';this.knock={x:0,y:0};this.deathTimer=0}
  hurtbox(){return{x:this.x-this.w/2,y:this.y-this.h/2,w:this.w,h:this.h}}
  takeDamage(amount,source,knock=0,id=''){if(this.dead||this.invuln>0)return false;this.hp-=amount;this.flash=.12;this.invuln=.08;const n=AMAHARA.U.norm(this.x-source.x,this.y-source.y);const resist=this.type==='heavy'?.35:1;this.knock={x:n.x*knock*resist,y:n.y*knock*resist};if(this.hp<=0){this.dead=true;this.state='dead';this.deathTimer=.5;this.game.onEnemyKilled(this);this.game.spawnBurst(this.x,this.y,'#6b3658',10)}else{this.state='hurt';this.timer=this.type==='heavy'?.08:.16}return true}
  update(dt){if(this.dead){this.deathTimer-=dt;return}this.invuln=Math.max(0,this.invuln-dt);this.flash=Math.max(0,this.flash-dt);if(this.stun>0){this.stun-=dt;return}if(this.state==='hurt'){this.timer-=dt;this.game.world.move(this,this.knock.x*dt,this.knock.y*dt);this.knock.x*=.82;this.knock.y*=.82;if(this.timer<=0)this.state='chase';return}const p=this.game.player,d=AMAHARA.U.dist(this,p);if(p.dead){this.state='idle';return}if(this.state==='idle'){this.timer-=dt;if(d<this.detection)this.state='chase';else if(this.timer<=0){this.timer=1+Math.random()*1.5}}
    else if(this.state==='chase'){if(d>this.disengage){this.state='idle';return}if(this.type==='archer'){if(d<82){const n=AMAHARA.U.norm(this.x-p.x,this.y-p.y);this.game.world.move(this,n.x*this.speed*dt,n.y*this.speed*dt)}else if(d>135){const n=AMAHARA.U.norm(p.x-this.x,p.y-this.y);this.game.world.move(this,n.x*this.speed*dt,n.y*this.speed*dt)}if(d<this.range&&this.game.requestEnemyAttack(this))this.startTelegraph()}else if(d>this.range){const n=AMAHARA.U.norm(p.x-this.x,p.y-this.y);this.game.world.move(this,n.x*this.speed*dt,n.y*this.speed*dt);this.facing=n.x>0?'right':'left'}else if(this.game.requestEnemyAttack(this))this.startTelegraph()}
    else if(this.state==='telegraph'){this.timer-=dt;if(this.timer<=0){this.state='attack';this.timer=this.type==='heavy'?.18:.12;this.attackId++;this.hitDone=false;if(this.type==='archer')this.fireArrow()}}
    else if(this.state==='attack'){this.timer-=dt;if(this.type!=='archer'&&!this.hitDone){const r={x:this.x-(this.facing==='left'?this.range:0),y:this.y-12,w:this.range+10,h:24};if(AMAHARA.U.rects(r,p.hurtbox())){this.hitDone=true;AMAHARA.Combat.damage(this.game,p,this.damage,this,this.type==='heavy'?110:65,this.attackId)}}if(this.timer<=0){this.state='recover';this.timer=this.recovery}}
    else if(this.state==='recover'){this.timer-=dt;if(this.timer<=0)this.state='chase'}
  }
  startTelegraph(){this.state='telegraph';this.timer=this.windup;this.facing=this.game.player.x>this.x?'right':'left'}
  fireArrow(){const p=this.game.player,n=AMAHARA.U.norm(p.x-this.x,p.y-this.y);this.game.projectiles.push({type:'arrow',x:this.x,y:this.y-8,vx:n.x*120,vy:n.y*120,w:8,h:4,life:2.4,damage:this.damage,owner:this,hit:new Set()});this.game.audio.tone(280,.08,'square',.05,-80)}
  draw(ctx){const x=Math.round(this.x),y=Math.round(this.y);ctx.save();ctx.translate(x,y);if(this.flash>0)ctx.globalAlpha=.55;ctx.fillStyle='#171a17';ctx.fillRect(-7,7,14,4);const c=this.type==='heavy'?'#505765':this.type==='runner'?'#6e524b':this.type==='archer'?'#55475f':'#5a6655';ctx.fillStyle=c;ctx.fillRect(-6,-8,12,14);ctx.fillStyle='#879174';ctx.fillRect(-4,-14,8,6);ctx.fillStyle='#402f35';ctx.fillRect(-5,-17,10,4);ctx.fillStyle='#7b365a';ctx.fillRect(-2,-12,3,3);if(this.type==='heavy'){ctx.fillStyle='#707985';ctx.fillRect(-9,-9,18,6);ctx.fillRect(-8,-16,16,4);ctx.fillStyle='#a48e64';ctx.fillRect(8,-7,3,13)}else if(this.type==='runner'){ctx.fillStyle='#9f7a5f';ctx.fillRect(6,-7,10,2)}else if(this.type==='archer'){ctx.strokeStyle='#9a7951';ctx.lineWidth=2;ctx.beginPath();ctx.arc(8,-6,8,-1.2,1.2);ctx.stroke()}else{ctx.fillStyle='#9d9b8d';ctx.fillRect(6,-6,10,2)}if(this.state==='telegraph'){ctx.fillStyle=this.type==='heavy'?'#f2b45a':'#d56b5f';ctx.fillRect(-7,-24,14,2)}ctx.restore();if(this.hp<this.maxHp&&!this.dead){ctx.fillStyle='#181818';ctx.fillRect(x-9,y-25,18,2);ctx.fillStyle='#9e3d3d';ctx.fillRect(x-9,y-25,18*(this.hp/this.maxHp),2)}}
};
