window.AMAHARA = window.AMAHARA || {};
AMAHARA.Player = class {
  constructor(game){this.game=game;this.x=500;this.y=1640;this.w=13;this.h=18;this.maxHp=AMAHARA.BALANCE.player.hp;this.hp=this.maxHp;this.maxEnergy=AMAHARA.BALANCE.player.energy;this.energy=this.maxEnergy;this.speed=AMAHARA.BALANCE.player.speed;this.facing='right';this.state='idle';this.dead=false;this.invuln=0;this.hurtTimer=0;this.dashTimer=0;this.dashCooldown=0;this.dashDir={x:1,y:0};this.attack=null;this.currentAttack=null;this.attackTimer=0;this.attackId=0;this.hitTargets=new Set();this.comboType=null;this.comboIndex=0;this.bufferedAttack=null;this.bufferTimer=0;this.magic1Cooldown=0;this.magic2Cooldown=0;this.flash=0;this.knock={x:0,y:0};this.hasSecret=false}
  reset(x=500,y=1640){this.x=x;this.y=y;this.hp=this.maxHp;this.energy=this.maxEnergy;this.dead=false;this.state='idle';this.attack=null;this.currentAttack=null;this.invuln=.8;this.knock={x:0,y:0}}
  canAct(){return !this.dead&&!['hurt','dash','attack'].includes(this.state)&&!this.game.dialogueActive&&!this.game.cutscene}
  update(dt,input){this.invuln=Math.max(0,this.invuln-dt);this.flash=Math.max(0,this.flash-dt);this.dashCooldown=Math.max(0,this.dashCooldown-dt);this.magic1Cooldown=Math.max(0,this.magic1Cooldown-dt);this.magic2Cooldown=Math.max(0,this.magic2Cooldown-dt);this.energy=Math.min(this.maxEnergy,this.energy+AMAHARA.BALANCE.player.energyRegen*dt);if(this.bufferTimer>0)this.bufferTimer-=dt;else this.bufferedAttack=null;
    if(this.dead)return;if(this.state==='hurt'){this.hurtTimer-=dt;this.game.world.move(this,this.knock.x*dt,this.knock.y*dt);this.knock.x*=.88;this.knock.y*=.88;if(this.hurtTimer<=0)this.state='idle';return}
    if(this.state==='dash'){this.dashTimer-=dt;this.game.world.move(this,this.dashDir.x*AMAHARA.BALANCE.player.dashSpeed*dt,this.dashDir.y*AMAHARA.BALANCE.player.dashSpeed*dt);this.game.spawnTrail(this.x,this.y,'#d7d7c8');if(this.dashTimer<=0)this.state='idle';return}
    if(this.state==='attack'){this.updateAttack(dt,input);return}
    const m=input.move();if(Math.abs(m.x)+Math.abs(m.y)>.05){this.state='move';this.game.world.move(this,m.x*this.speed*dt,m.y*this.speed*dt);if(Math.abs(m.x)>Math.abs(m.y))this.facing=m.x>0?'right':'left';else this.facing=m.y>0?'down':'up'}else this.state='idle';
    if(input.take('dash'))this.startDash(m);else if(input.take('light'))this.startCombo('light');else if(input.take('heavy'))this.startCombo('heavy');else if(input.take('magic1'))this.castSlash();else if(input.take('magic2'))this.castSeal();
  }
  startDash(m){if(this.dashCooldown>0)return;let d=m;if(Math.hypot(d.x,d.y)<.1)d=this.facing==='right'?{x:1,y:0}:this.facing==='left'?{x:-1,y:0}:this.facing==='down'?{x:0,y:1}:{x:0,y:-1};this.dashDir=AMAHARA.U.norm(d.x,d.y);this.state='dash';this.dashTimer=AMAHARA.BALANCE.player.dashDuration;this.dashCooldown=AMAHARA.BALANCE.player.dashCooldown;this.invuln=this.dashTimer;this.game.audio.sfx('dash')}
  startCombo(type){this.comboType=type;this.comboIndex=0;this.beginAttack(AMAHARA.BALANCE.combos[type][0])}
  beginAttack(a){this.state='attack';this.currentAttack=a;this.attackTimer=0;this.attackPhase='startup';this.attackId++;this.hitTargets.clear();this.bufferedAttack=null;this.game.audio.sfx(this.comboType==='heavy'?'heavy':'slash')}
  updateAttack(dt,input){this.attackTimer+=dt;const a=this.currentAttack;if(input.take(this.comboType)){this.bufferedAttack=this.comboType;this.bufferTimer=.32}else if(input.take(this.comboType==='light'?'heavy':'light')){this.bufferedAttack=null}
    if(this.attackPhase==='startup'&&this.attackTimer>=a.startup){this.attackPhase='active';this.attackTimer=0;this.game.world.move(this,(this.facing==='right'?1:this.facing==='left'?-1:0)*a.step,(this.facing==='down'?1:this.facing==='up'?-1:0)*a.step)}
    else if(this.attackPhase==='active'){this.applyAttackHit();if(this.attackTimer>=a.active){this.attackPhase='recovery';this.attackTimer=0}}
    else if(this.attackPhase==='recovery'&&this.attackTimer>=a.recovery){if(this.bufferedAttack&&this.comboIndex<AMAHARA.BALANCE.combos[this.comboType].length-1){this.comboIndex++;this.beginAttack(AMAHARA.BALANCE.combos[this.comboType][this.comboIndex])}else{this.state='idle';this.currentAttack=null;this.comboType=null;this.comboIndex=0}}
  }
  applyAttackHit(){const rect=AMAHARA.Combat.attackRect(this,this.currentAttack);for(const e of this.game.enemies){if(e.dead||this.hitTargets.has(e.id))continue;if(AMAHARA.U.rects(rect,e.hurtbox())){this.hitTargets.add(e.id);AMAHARA.Combat.damage(this.game,e,this.currentAttack.damage,this,this.currentAttack.knockback,this.attackId);this.energy=Math.min(this.maxEnergy,this.energy+AMAHARA.BALANCE.player.energyOnHit)}}const b=this.game.boss;if(b&&!b.dead&&!this.hitTargets.has(b.id)&&AMAHARA.U.rects(rect,b.hurtbox())){this.hitTargets.add(b.id);AMAHARA.Combat.damage(this.game,b,this.currentAttack.damage,this,this.currentAttack.knockback,this.attackId);this.energy=Math.min(this.maxEnergy,this.energy+AMAHARA.BALANCE.player.energyOnHit)}}
  castSlash(){const m=AMAHARA.BALANCE.magic.slash;if(this.magic1Cooldown>0||this.energy<m.cost)return this.game.toast('Energia divina insuficiente');this.energy-=m.cost;this.magic1Cooldown=m.cooldown;const d=this.facing==='right'?{x:1,y:0}:this.facing==='left'?{x:-1,y:0}:this.facing==='down'?{x:0,y:1}:{x:0,y:-1};this.game.projectiles.push({type:'playerSlash',x:this.x+d.x*18,y:this.y-4+d.y*18,vx:d.x*m.speed,vy:d.y*m.speed,w:20,h:12,life:m.life,damage:m.damage,owner:this,hit:new Set()});this.game.audio.sfx('magic1');this.game.spawnBurst(this.x,this.y,'#9de3e0',8)}
  castSeal(){const m=AMAHARA.BALANCE.magic.seal;if(this.magic2Cooldown>0||this.energy<m.cost)return this.game.toast('Energia divina insuficiente');this.energy-=m.cost;this.magic2Cooldown=m.cooldown;this.game.rings.push({x:this.x,y:this.y,r:4,max:m.radius,life:.4,color:'#d59b59'});for(const e of this.game.enemies)if(!e.dead&&AMAHARA.U.dist(this,e)<m.radius){AMAHARA.Combat.damage(this.game,e,m.damage,this,75,'seal');e.stun=Math.max(e.stun||0,m.stun)}if(this.game.boss&&!this.game.boss.dead&&AMAHARA.U.dist(this,this.game.boss)<m.radius)AMAHARA.Combat.damage(this.game,this.game.boss,m.damage*.7,this,40,'seal');this.game.audio.sfx('magic2');this.game.spawnBurst(this.x,this.y,'#e6b55f',18)}
  takeDamage(amount,source,knock=0,id=''){if(this.invuln>0||this.dead)return false;this.hp=Math.max(0,this.hp-amount);this.flash=.15;this.invuln=AMAHARA.BALANCE.player.hitIFrames;const n=source?AMAHARA.U.norm(this.x-source.x,this.y-source.y):{x:0,y:0};this.knock={x:n.x*knock,y:n.y*knock};if(this.hp<=0){this.dead=true;this.state='dead';this.game.onPlayerDeath()}else{this.state='hurt';this.hurtTimer=.22}return true}
  hurtbox(){return{x:this.x-this.w/2,y:this.y-this.h/2,w:this.w,h:this.h}}
  draw(ctx){const x=Math.round(this.x),y=Math.round(this.y);ctx.save();ctx.translate(x,y);if(this.invuln>0&&Math.floor(this.invuln*20)%2===0)ctx.globalAlpha=.55; // shadow
    ctx.fillStyle='#1a1c19';ctx.fillRect(-8,7,16,4); // legs
    const step=this.state==='move'?(Math.sin(performance.now()/75)>0?1:-1):0;
    ctx.fillStyle='#2b3133';ctx.fillRect(-6,2+step,5,9);ctx.fillRect(1,2-step,5,9); // hakama
    ctx.fillStyle='#6b2630';ctx.fillRect(-7,-9,14,12);ctx.fillStyle='#a23b39';ctx.fillRect(-6,-8,5,9); // torso
    ctx.fillStyle='#c7a07d';ctx.fillRect(-4,-15,8,6);ctx.fillStyle='#1e2325';ctx.fillRect(-5,-18,10,4); // hair
    ctx.fillStyle='#d9b05e';ctx.fillRect(4,-9,2,10);ctx.fillStyle='#d9b05e';ctx.fillRect(5,-18,2,3); // divine mark
    // katana
    const fx=this.facing==='left'?-1:1;ctx.fillStyle='#d8d8d1';ctx.fillRect(fx>0?7:-18,-4,11,2);ctx.fillStyle='#72502d';ctx.fillRect(fx>0?5:-8,-3,3,4);
    if(this.state==='attack'&&this.attackPhase==='active'){ctx.strokeStyle=this.comboType==='heavy'?'#f1c46b':'#e7ebe1';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-4,this.currentAttack.reach+9,this.facing==='up'?Math.PI*1.1:this.facing==='down'?.1:this.facing==='left'?Math.PI*.65:-Math.PI*.35,this.facing==='up'?Math.PI*1.9:this.facing==='down'?Math.PI*.9:this.facing==='left'?Math.PI*1.35:Math.PI*.35);ctx.stroke()}
    ctx.restore()}
};
